<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>DoonvHelper</AssemblyName>
        <RootNamespace>Celeste.Mod.DoonvHelper</RootNamespace>
        <LangVersion>latest</LangVersion>
        <CelestePrefix Condition="'$(CelestePrefix)' == '' And Exists('..\..\Celeste.exe')">..\..</CelestePrefix>
        <CelestePrefix Condition="'$(CelestePrefix)' == ''">lib-stripped</CelestePrefix>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>bin</OutputPath>
        <PathMap>$(MSBuildProjectDirectory)=DoonvHelper/</PathMap>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <PackageReference PrivateAssets="all" ExcludeAssets="runtime" />
        <Reference Private="false" />
    </ItemDefinitionGroup>

    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.1" />
        <PackageReference Include="MonoMod.Patcher" Version="25.0.0-prerelease.2" />
        <PackageReference Include="CelesteAnalyzer" Version="*" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Celeste" HintPath="$(CelestePrefix)\Celeste.dll" />
        <Reference Include="FNA" HintPath="$(CelestePrefix)\FNA.dll" />
        <Reference Include="MMHOOK_Celeste" HintPath="$(CelestePrefix)\MMHOOK_Celeste.dll" />
        <Reference Include="Guneline" HintPath="$(CelestePrefix)\Mods\Cache\Guneline.Guneline.dll" />
        <Reference Include="LuaCutscenes" HintPath="$(CelestePrefix)\Mods\Cache\LuaCutscenes.LuaCutscenes.dll" />
        <Reference Include="XaphanHelper" HintPath="$(CelestePrefix)\Mods\Cache\XaphanHelper.XaphanHelper.dll" />
    </ItemGroup>
</Project>