<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>DoonvHelper</AssemblyName>
        <RootNamespace>Celeste.Mod.DoonvHelper</RootNamespace>
        <LangVersion>latest</LangVersion>
        <CelestePrefix Condition="'$(CelestePrefix)' == '' And Exists('..\..\Celeste.exe')">..\..</CelestePrefix>
        <CelestePrefix Condition="'$(CelestePrefix)' == ''">lib-stripped</CelestePrefix>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>bin</OutputPath>
    </PropertyGroup>

    <!--Disable
    "Copy Local" for all references-->
    <ItemDefinitionGroup>
        <PackageReference PrivateAssets="all" ExcludeAssets="runtime" />
        <Reference Private="false" />
    </ItemDefinitionGroup>

    <ItemGroup>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.2.3" PrivateAssets="all" ExcludeAssets="runtime">
          <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MonoMod.Patcher" Version="25.0.0-prerelease.2" />
        <PackageReference Include="CelesteAnalyzer" Version="*" />
        <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Celeste">
          <HintPath>..\..\Celeste.dll</HintPath>
        </Reference>
        <Reference Include="FNA">
          <HintPath>..\..\FNA.dll</HintPath>
        </Reference>
        <Reference Include="Guneline">
            <HintPath>../Cache/Guneline.Guneline.dll</HintPath>
        </Reference>
        <Reference Include="LuaCutscenes">
            <HintPath>../Cache/LuaCutscenes.LuaCutscenes.dll</HintPath>
        </Reference>
        <Reference Include="MMHOOK_Celeste">
          <HintPath>..\..\MMHOOK_Celeste.dll</HintPath>
        </Reference>
        <Reference Include="XaphanHelper">
            <HintPath>../Cache/XaphanHelper.XaphanHelper.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyFiles" AfterTargets="Build">
        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFolder="bin" />
        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).pdb" DestinationFolder="bin" />
    </Target>

    <PropertyGroup>
        <PathMap>$(MSBuildProjectDirectory)=DoonvHelper/</PathMap>
    </PropertyGroup>

    <PropertyGroup>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    </PropertyGroup>

</Project>